# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: track
version: '0.0.0'
github: "dcerjan/track"
license: MIT
author: "Domagoj Cerjan &lt;domagoj.cerjan@gmail.com&gt;"
maintainer: "Domagoj Cerjan &lt;domagoj.cerjan@gmail.com&gt;"
# synopsis: A new Haskeleton package.
# description: track is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - aeson
  - optparse-applicative
  - unix-time
  - bytestring
  - text
  - lens
  - ansi-wl-pprint
  source-dirs: library

executables:
  track:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - track
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  track-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - track
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  track-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - track
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
